// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: client.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_NOT_FOUND ErrorCode = 0
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"NOT_FOUND": 0,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type GetShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShoppingListRequest) Reset() {
	*x = GetShoppingListRequest{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListRequest) ProtoMessage() {}

func (x *GetShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListRequest.ProtoReflect.Descriptor instead.
func (*GetShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubscribeShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeShoppingListRequest) Reset() {
	*x = SubscribeShoppingListRequest{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeShoppingListRequest) ProtoMessage() {}

func (x *SubscribeShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeShoppingListRequest.ProtoReflect.Descriptor instead.
func (*SubscribeShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

type ClientRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*ClientRequest_ShoppingList
	//	*ClientRequest_GetShoppingList_
	//	*ClientRequest_SubscribeShoppingList
	RequestType   isClientRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *ClientRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientRequest) GetRequestType() isClientRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *ClientRequest) GetShoppingList() *ShoppingList {
	if x != nil {
		if x, ok := x.RequestType.(*ClientRequest_ShoppingList); ok {
			return x.ShoppingList
		}
	}
	return nil
}

func (x *ClientRequest) GetGetShoppingList_() *GetShoppingListRequest {
	if x != nil {
		if x, ok := x.RequestType.(*ClientRequest_GetShoppingList_); ok {
			return x.GetShoppingList_
		}
	}
	return nil
}

func (x *ClientRequest) GetSubscribeShoppingList() *SubscribeShoppingListRequest {
	if x != nil {
		if x, ok := x.RequestType.(*ClientRequest_SubscribeShoppingList); ok {
			return x.SubscribeShoppingList
		}
	}
	return nil
}

type isClientRequest_RequestType interface {
	isClientRequest_RequestType()
}

type ClientRequest_ShoppingList struct {
	ShoppingList *ShoppingList `protobuf:"bytes,2,opt,name=shopping_list,json=shoppingList,proto3,oneof"`
}

type ClientRequest_GetShoppingList_ struct {
	GetShoppingList_ *GetShoppingListRequest `protobuf:"bytes,3,opt,name=get_shopping_list,json=getShoppingList,proto3,oneof"`
}

type ClientRequest_SubscribeShoppingList struct {
	SubscribeShoppingList *SubscribeShoppingListRequest `protobuf:"bytes,4,opt,name=subscribe_shopping_list,json=subscribeShoppingList,proto3,oneof"`
}

func (*ClientRequest_ShoppingList) isClientRequest_RequestType() {}

func (*ClientRequest_GetShoppingList_) isClientRequest_RequestType() {}

func (*ClientRequest_SubscribeShoppingList) isClientRequest_RequestType() {}

type ServerResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*ServerResponse_ShoppingList
	//	*ServerResponse_Error
	ResponseType  isServerResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ServerResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ServerResponse) GetResponseType() isServerResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *ServerResponse) GetShoppingList() *ShoppingList {
	if x != nil {
		if x, ok := x.ResponseType.(*ServerResponse_ShoppingList); ok {
			return x.ShoppingList
		}
	}
	return nil
}

func (x *ServerResponse) GetError() ErrorCode {
	if x != nil {
		if x, ok := x.ResponseType.(*ServerResponse_Error); ok {
			return x.Error
		}
	}
	return ErrorCode_NOT_FOUND
}

type isServerResponse_ResponseType interface {
	isServerResponse_ResponseType()
}

type ServerResponse_ShoppingList struct {
	ShoppingList *ShoppingList `protobuf:"bytes,2,opt,name=shopping_list,json=shoppingList,proto3,oneof"`
}

type ServerResponse_Error struct {
	Error ErrorCode `protobuf:"varint,3,opt,name=error,proto3,enum=ErrorCode,oneof"`
}

func (*ServerResponse_ShoppingList) isServerResponse_ResponseType() {}

func (*ServerResponse_Error) isServerResponse_ResponseType() {}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x1a\x0eshopping.proto\"(\n" +
	"\x16GetShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cSubscribeShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x04\n" +
	"\x02Ok\"\x94\x02\n" +
	"\rClientRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x124\n" +
	"\rshopping_list\x18\x02 \x01(\v2\r.ShoppingListH\x00R\fshoppingList\x12E\n" +
	"\x11get_shopping_list\x18\x03 \x01(\v2\x17.GetShoppingListRequestH\x00R\x0fgetShoppingList\x12W\n" +
	"\x17subscribe_shopping_list\x18\x04 \x01(\v2\x1d.SubscribeShoppingListRequestH\x00R\x15subscribeShoppingListB\x0e\n" +
	"\frequest_type\"\x9a\x01\n" +
	"\x0eServerResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x124\n" +
	"\rshopping_list\x18\x02 \x01(\v2\r.ShoppingListH\x00R\fshoppingList\x12\"\n" +
	"\x05error\x18\x03 \x01(\x0e2\n" +
	".ErrorCodeH\x00R\x05errorB\x0f\n" +
	"\rresponse_type*\x1a\n" +
	"\tErrorCode\x12\r\n" +
	"\tNOT_FOUND\x10\x00B'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_client_proto_goTypes = []any{
	(ErrorCode)(0),                       // 0: ErrorCode
	(*GetShoppingListRequest)(nil),       // 1: GetShoppingListRequest
	(*SubscribeShoppingListRequest)(nil), // 2: SubscribeShoppingListRequest
	(*Ok)(nil),                           // 3: Ok
	(*ClientRequest)(nil),                // 4: ClientRequest
	(*ServerResponse)(nil),               // 5: ServerResponse
	(*ShoppingList)(nil),                 // 6: ShoppingList
}
var file_client_proto_depIdxs = []int32{
	6, // 0: ClientRequest.shopping_list:type_name -> ShoppingList
	1, // 1: ClientRequest.get_shopping_list:type_name -> GetShoppingListRequest
	2, // 2: ClientRequest.subscribe_shopping_list:type_name -> SubscribeShoppingListRequest
	6, // 3: ServerResponse.shopping_list:type_name -> ShoppingList
	0, // 4: ServerResponse.error:type_name -> ErrorCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_shopping_proto_init()
	file_client_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientRequest_ShoppingList)(nil),
		(*ClientRequest_GetShoppingList_)(nil),
		(*ClientRequest_SubscribeShoppingList)(nil),
	}
	file_client_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerResponse_ShoppingList)(nil),
		(*ServerResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
