// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: client.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShoppingListRequest) Reset() {
	*x = GetShoppingListRequest{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListRequest) ProtoMessage() {}

func (x *GetShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListRequest.ProtoReflect.Descriptor instead.
func (*GetShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*ClientRequest_ShoppingList
	//	*ClientRequest_GetShoppingList_
	RequestType   isClientRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetRequestType() isClientRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *ClientRequest) GetShoppingList() *ShoppingList {
	if x != nil {
		if x, ok := x.RequestType.(*ClientRequest_ShoppingList); ok {
			return x.ShoppingList
		}
	}
	return nil
}

func (x *ClientRequest) GetGetShoppingList_() *GetShoppingListRequest {
	if x != nil {
		if x, ok := x.RequestType.(*ClientRequest_GetShoppingList_); ok {
			return x.GetShoppingList_
		}
	}
	return nil
}

type isClientRequest_RequestType interface {
	isClientRequest_RequestType()
}

type ClientRequest_ShoppingList struct {
	ShoppingList *ShoppingList `protobuf:"bytes,1,opt,name=shopping_list,json=shoppingList,proto3,oneof"`
}

type ClientRequest_GetShoppingList_ struct {
	GetShoppingList_ *GetShoppingListRequest `protobuf:"bytes,2,opt,name=get_shopping_list,json=getShoppingList,proto3,oneof"`
}

func (*ClientRequest_ShoppingList) isClientRequest_RequestType() {}

func (*ClientRequest_GetShoppingList_) isClientRequest_RequestType() {}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x1a\x0eshopping.proto\"(\n" +
	"\x16GetShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x01\n" +
	"\rClientRequest\x124\n" +
	"\rshopping_list\x18\x01 \x01(\v2\r.ShoppingListH\x00R\fshoppingList\x12E\n" +
	"\x11get_shopping_list\x18\x02 \x01(\v2\x17.GetShoppingListRequestH\x00R\x0fgetShoppingListB\x0e\n" +
	"\frequest_typeB'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_proto_goTypes = []any{
	(*GetShoppingListRequest)(nil), // 0: GetShoppingListRequest
	(*ClientRequest)(nil),          // 1: ClientRequest
	(*ShoppingList)(nil),           // 2: ShoppingList
}
var file_client_proto_depIdxs = []int32{
	2, // 0: ClientRequest.shopping_list:type_name -> ShoppingList
	0, // 1: ClientRequest.get_shopping_list:type_name -> GetShoppingListRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_shopping_proto_init()
	file_client_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientRequest_ShoppingList)(nil),
		(*ClientRequest_GetShoppingList_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
