// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: crdt.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dot) Reset() {
	*x = Dot{}
	mi := &file_crdt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dot) ProtoMessage() {}

func (x *Dot) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dot.ProtoReflect.Descriptor instead.
func (*Dot) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{0}
}

func (x *Dot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dot) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DotContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionVector map[string]uint32      `protobuf:"bytes,1,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Dots          []*Dot                 `protobuf:"bytes,2,rep,name=dots,proto3" json:"dots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DotContext) Reset() {
	*x = DotContext{}
	mi := &file_crdt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotContext) ProtoMessage() {}

func (x *DotContext) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotContext.ProtoReflect.Descriptor instead.
func (*DotContext) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{1}
}

func (x *DotContext) GetVersionVector() map[string]uint32 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *DotContext) GetDots() []*Dot {
	if x != nil {
		return x.Dots
	}
	return nil
}

type DotKernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKeys       []*Dot                 `protobuf:"bytes,1,rep,name=dot_keys,json=dotKeys,proto3" json:"dot_keys,omitempty"`
	DotValues     []string               `protobuf:"bytes,2,rep,name=dot_values,json=dotValues,proto3" json:"dot_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DotKernel) Reset() {
	*x = DotKernel{}
	mi := &file_crdt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotKernel) ProtoMessage() {}

func (x *DotKernel) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotKernel.ProtoReflect.Descriptor instead.
func (*DotKernel) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{2}
}

func (x *DotKernel) GetDotKeys() []*Dot {
	if x != nil {
		return x.DotKeys
	}
	return nil
}

func (x *DotKernel) GetDotValues() []string {
	if x != nil {
		return x.DotValues
	}
	return nil
}

type CCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKernel     *DotKernel             `protobuf:"bytes,1,opt,name=dot_kernel,json=dotKernel,proto3" json:"dot_kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCounter) Reset() {
	*x = CCounter{}
	mi := &file_crdt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCounter) ProtoMessage() {}

func (x *CCounter) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCounter.ProtoReflect.Descriptor instead.
func (*CCounter) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{3}
}

func (x *CCounter) GetDotKernel() *DotKernel {
	if x != nil {
		return x.DotKernel
	}
	return nil
}

var File_crdt_proto protoreflect.FileDescriptor

const file_crdt_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"crdt.proto\"'\n" +
	"\x03Dot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"\xaf\x01\n" +
	"\n" +
	"DotContext\x12E\n" +
	"\x0eversion_vector\x18\x01 \x03(\v2\x1e.DotContext.VersionVectorEntryR\rversionVector\x12\x18\n" +
	"\x04dots\x18\x02 \x03(\v2\x04.DotR\x04dots\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"K\n" +
	"\tDotKernel\x12\x1f\n" +
	"\bdot_keys\x18\x01 \x03(\v2\x04.DotR\adotKeys\x12\x1d\n" +
	"\n" +
	"dot_values\x18\x02 \x03(\tR\tdotValues\"5\n" +
	"\bCCounter\x12)\n" +
	"\n" +
	"dot_kernel\x18\x01 \x01(\v2\n" +
	".DotKernelR\tdotKernelB'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_crdt_proto_rawDescOnce sync.Once
	file_crdt_proto_rawDescData []byte
)

func file_crdt_proto_rawDescGZIP() []byte {
	file_crdt_proto_rawDescOnce.Do(func() {
		file_crdt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)))
	})
	return file_crdt_proto_rawDescData
}

var file_crdt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crdt_proto_goTypes = []any{
	(*Dot)(nil),        // 0: Dot
	(*DotContext)(nil), // 1: DotContext
	(*DotKernel)(nil),  // 2: DotKernel
	(*CCounter)(nil),   // 3: CCounter
	nil,                // 4: DotContext.VersionVectorEntry
}
var file_crdt_proto_depIdxs = []int32{
	4, // 0: DotContext.version_vector:type_name -> DotContext.VersionVectorEntry
	0, // 1: DotContext.dots:type_name -> Dot
	0, // 2: DotKernel.dot_keys:type_name -> Dot
	2, // 3: CCounter.dot_kernel:type_name -> DotKernel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_crdt_proto_init() }
func file_crdt_proto_init() {
	if File_crdt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crdt_proto_goTypes,
		DependencyIndexes: file_crdt_proto_depIdxs,
		MessageInfos:      file_crdt_proto_msgTypes,
	}.Build()
	File_crdt_proto = out.File
	file_crdt_proto_goTypes = nil
	file_crdt_proto_depIdxs = nil
}
