// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: crdt.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dot) Reset() {
	*x = Dot{}
	mi := &file_crdt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dot) ProtoMessage() {}

func (x *Dot) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dot.ProtoReflect.Descriptor instead.
func (*Dot) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{0}
}

func (x *Dot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dot) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DotContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionVector map[string]uint32      `protobuf:"bytes,1,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Dots          []*Dot                 `protobuf:"bytes,2,rep,name=dots,proto3" json:"dots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DotContext) Reset() {
	*x = DotContext{}
	mi := &file_crdt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotContext) ProtoMessage() {}

func (x *DotContext) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotContext.ProtoReflect.Descriptor instead.
func (*DotContext) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{1}
}

func (x *DotContext) GetVersionVector() map[string]uint32 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *DotContext) GetDots() []*Dot {
	if x != nil {
		return x.Dots
	}
	return nil
}

type IntDotKernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKeys       []*Dot                 `protobuf:"bytes,1,rep,name=dot_keys,json=dotKeys,proto3" json:"dot_keys,omitempty"`
	DotValues     []int64                `protobuf:"varint,2,rep,packed,name=dot_values,json=dotValues,proto3" json:"dot_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntDotKernel) Reset() {
	*x = IntDotKernel{}
	mi := &file_crdt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntDotKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntDotKernel) ProtoMessage() {}

func (x *IntDotKernel) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntDotKernel.ProtoReflect.Descriptor instead.
func (*IntDotKernel) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{2}
}

func (x *IntDotKernel) GetDotKeys() []*Dot {
	if x != nil {
		return x.DotKeys
	}
	return nil
}

func (x *IntDotKernel) GetDotValues() []int64 {
	if x != nil {
		return x.DotValues
	}
	return nil
}

type StringDotKernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKeys       []*Dot                 `protobuf:"bytes,1,rep,name=dot_keys,json=dotKeys,proto3" json:"dot_keys,omitempty"`
	DotValues     []string               `protobuf:"bytes,2,rep,name=dot_values,json=dotValues,proto3" json:"dot_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringDotKernel) Reset() {
	*x = StringDotKernel{}
	mi := &file_crdt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringDotKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDotKernel) ProtoMessage() {}

func (x *StringDotKernel) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDotKernel.ProtoReflect.Descriptor instead.
func (*StringDotKernel) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{3}
}

func (x *StringDotKernel) GetDotKeys() []*Dot {
	if x != nil {
		return x.DotKeys
	}
	return nil
}

func (x *StringDotKernel) GetDotValues() []string {
	if x != nil {
		return x.DotValues
	}
	return nil
}

type EmptyDotKernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKeys       []*Dot                 `protobuf:"bytes,1,rep,name=dot_keys,json=dotKeys,proto3" json:"dot_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyDotKernel) Reset() {
	*x = EmptyDotKernel{}
	mi := &file_crdt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyDotKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyDotKernel) ProtoMessage() {}

func (x *EmptyDotKernel) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyDotKernel.ProtoReflect.Descriptor instead.
func (*EmptyDotKernel) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{4}
}

func (x *EmptyDotKernel) GetDotKeys() []*Dot {
	if x != nil {
		return x.DotKeys
	}
	return nil
}

type CCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKernel     *IntDotKernel          `protobuf:"bytes,1,opt,name=dot_kernel,json=dotKernel,proto3" json:"dot_kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCounter) Reset() {
	*x = CCounter{}
	mi := &file_crdt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCounter) ProtoMessage() {}

func (x *CCounter) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCounter.ProtoReflect.Descriptor instead.
func (*CCounter) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{5}
}

func (x *CCounter) GetDotKernel() *IntDotKernel {
	if x != nil {
		return x.DotKernel
	}
	return nil
}

type StringMVReg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKernel     *StringDotKernel       `protobuf:"bytes,1,opt,name=dot_kernel,json=dotKernel,proto3" json:"dot_kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMVReg) Reset() {
	*x = StringMVReg{}
	mi := &file_crdt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMVReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMVReg) ProtoMessage() {}

func (x *StringMVReg) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMVReg.ProtoReflect.Descriptor instead.
func (*StringMVReg) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{6}
}

func (x *StringMVReg) GetDotKernel() *StringDotKernel {
	if x != nil {
		return x.DotKernel
	}
	return nil
}

type EWFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotKernel     *EmptyDotKernel        `protobuf:"bytes,1,opt,name=dot_kernel,json=dotKernel,proto3" json:"dot_kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EWFlag) Reset() {
	*x = EWFlag{}
	mi := &file_crdt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EWFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EWFlag) ProtoMessage() {}

func (x *EWFlag) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EWFlag.ProtoReflect.Descriptor instead.
func (*EWFlag) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{7}
}

func (x *EWFlag) GetDotKernel() *EmptyDotKernel {
	if x != nil {
		return x.DotKernel
	}
	return nil
}

var File_crdt_proto protoreflect.FileDescriptor

const file_crdt_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"crdt.proto\"'\n" +
	"\x03Dot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"\xaf\x01\n" +
	"\n" +
	"DotContext\x12E\n" +
	"\x0eversion_vector\x18\x01 \x03(\v2\x1e.DotContext.VersionVectorEntryR\rversionVector\x12\x18\n" +
	"\x04dots\x18\x02 \x03(\v2\x04.DotR\x04dots\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"N\n" +
	"\fIntDotKernel\x12\x1f\n" +
	"\bdot_keys\x18\x01 \x03(\v2\x04.DotR\adotKeys\x12\x1d\n" +
	"\n" +
	"dot_values\x18\x02 \x03(\x03R\tdotValues\"Q\n" +
	"\x0fStringDotKernel\x12\x1f\n" +
	"\bdot_keys\x18\x01 \x03(\v2\x04.DotR\adotKeys\x12\x1d\n" +
	"\n" +
	"dot_values\x18\x02 \x03(\tR\tdotValues\"1\n" +
	"\x0eEmptyDotKernel\x12\x1f\n" +
	"\bdot_keys\x18\x01 \x03(\v2\x04.DotR\adotKeys\"8\n" +
	"\bCCounter\x12,\n" +
	"\n" +
	"dot_kernel\x18\x01 \x01(\v2\r.IntDotKernelR\tdotKernel\">\n" +
	"\vStringMVReg\x12/\n" +
	"\n" +
	"dot_kernel\x18\x01 \x01(\v2\x10.StringDotKernelR\tdotKernel\"8\n" +
	"\x06EWFlag\x12.\n" +
	"\n" +
	"dot_kernel\x18\x01 \x01(\v2\x0f.EmptyDotKernelR\tdotKernelB'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_crdt_proto_rawDescOnce sync.Once
	file_crdt_proto_rawDescData []byte
)

func file_crdt_proto_rawDescGZIP() []byte {
	file_crdt_proto_rawDescOnce.Do(func() {
		file_crdt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)))
	})
	return file_crdt_proto_rawDescData
}

var file_crdt_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_crdt_proto_goTypes = []any{
	(*Dot)(nil),             // 0: Dot
	(*DotContext)(nil),      // 1: DotContext
	(*IntDotKernel)(nil),    // 2: IntDotKernel
	(*StringDotKernel)(nil), // 3: StringDotKernel
	(*EmptyDotKernel)(nil),  // 4: EmptyDotKernel
	(*CCounter)(nil),        // 5: CCounter
	(*StringMVReg)(nil),     // 6: StringMVReg
	(*EWFlag)(nil),          // 7: EWFlag
	nil,                     // 8: DotContext.VersionVectorEntry
}
var file_crdt_proto_depIdxs = []int32{
	8, // 0: DotContext.version_vector:type_name -> DotContext.VersionVectorEntry
	0, // 1: DotContext.dots:type_name -> Dot
	0, // 2: IntDotKernel.dot_keys:type_name -> Dot
	0, // 3: StringDotKernel.dot_keys:type_name -> Dot
	0, // 4: EmptyDotKernel.dot_keys:type_name -> Dot
	2, // 5: CCounter.dot_kernel:type_name -> IntDotKernel
	3, // 6: StringMVReg.dot_kernel:type_name -> StringDotKernel
	4, // 7: EWFlag.dot_kernel:type_name -> EmptyDotKernel
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_crdt_proto_init() }
func file_crdt_proto_init() {
	if File_crdt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crdt_proto_goTypes,
		DependencyIndexes: file_crdt_proto_depIdxs,
		MessageInfos:      file_crdt_proto_msgTypes,
	}.Build()
	File_crdt_proto = out.File
	file_crdt_proto_goTypes = nil
	file_crdt_proto_depIdxs = nil
}
