// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: node.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Origin string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"` // id of the node that sent the request
	// Types that are valid to be assigned to RequestType:
	//
	//	*Request_Ping
	//	*Request_FetchRing
	//	*Request_GetHashSpace
	//	*Request_GossipJoin
	//	*Request_Get
	//	*Request_Put
	//	*Request_Delete
	//	*Request_Has
	RequestType   isRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Request) GetRequestType() isRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *Request) GetPing() *RequestPing {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Request) GetFetchRing() *RequestFetchRing {
	if x != nil {
		if x, ok := x.RequestType.(*Request_FetchRing); ok {
			return x.FetchRing
		}
	}
	return nil
}

func (x *Request) GetGetHashSpace() *RequestGetHashSpace {
	if x != nil {
		if x, ok := x.RequestType.(*Request_GetHashSpace); ok {
			return x.GetHashSpace
		}
	}
	return nil
}

func (x *Request) GetGossipJoin() *RequestGossipJoin {
	if x != nil {
		if x, ok := x.RequestType.(*Request_GossipJoin); ok {
			return x.GossipJoin
		}
	}
	return nil
}

func (x *Request) GetGet() *RequestGet {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Request) GetPut() *RequestPut {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Request) GetDelete() *RequestDelete {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Request) GetHas() *RequestHas {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Has); ok {
			return x.Has
		}
	}
	return nil
}

type isRequest_RequestType interface {
	isRequest_RequestType()
}

type Request_Ping struct {
	Ping *RequestPing `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

type Request_FetchRing struct {
	FetchRing *RequestFetchRing `protobuf:"bytes,12,opt,name=fetch_ring,json=fetchRing,proto3,oneof"`
}

type Request_GetHashSpace struct {
	GetHashSpace *RequestGetHashSpace `protobuf:"bytes,13,opt,name=get_hash_space,json=getHashSpace,proto3,oneof"`
}

type Request_GossipJoin struct {
	GossipJoin *RequestGossipJoin `protobuf:"bytes,14,opt,name=gossip_join,json=gossipJoin,proto3,oneof"`
}

type Request_Get struct {
	Get *RequestGet `protobuf:"bytes,15,opt,name=get,proto3,oneof"`
}

type Request_Put struct {
	Put *RequestPut `protobuf:"bytes,16,opt,name=put,proto3,oneof"`
}

type Request_Delete struct {
	Delete *RequestDelete `protobuf:"bytes,17,opt,name=delete,proto3,oneof"`
}

type Request_Has struct {
	Has *RequestHas `protobuf:"bytes,18,opt,name=has,proto3,oneof"`
}

func (*Request_Ping) isRequest_RequestType() {}

func (*Request_FetchRing) isRequest_RequestType() {}

func (*Request_GetHashSpace) isRequest_RequestType() {}

func (*Request_GossipJoin) isRequest_RequestType() {}

func (*Request_Get) isRequest_RequestType() {}

func (*Request_Put) isRequest_RequestType() {}

func (*Request_Delete) isRequest_RequestType() {}

func (*Request_Has) isRequest_RequestType() {}

type RequestPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPing) Reset() {
	*x = RequestPing{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPing) ProtoMessage() {}

func (x *RequestPing) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPing.ProtoReflect.Descriptor instead.
func (*RequestPing) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

type RequestFetchRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFetchRing) Reset() {
	*x = RequestFetchRing{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFetchRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFetchRing) ProtoMessage() {}

func (x *RequestFetchRing) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFetchRing.ProtoReflect.Descriptor instead.
func (*RequestFetchRing) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

type RequestGetHashSpace struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartHashSpace uint64                 `protobuf:"varint,1,opt,name=start_hash_space,json=startHashSpace,proto3" json:"start_hash_space,omitempty"`
	EndHashSpace   uint64                 `protobuf:"varint,2,opt,name=end_hash_space,json=endHashSpace,proto3" json:"end_hash_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestGetHashSpace) Reset() {
	*x = RequestGetHashSpace{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetHashSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetHashSpace) ProtoMessage() {}

func (x *RequestGetHashSpace) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetHashSpace.ProtoReflect.Descriptor instead.
func (*RequestGetHashSpace) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *RequestGetHashSpace) GetStartHashSpace() uint64 {
	if x != nil {
		return x.StartHashSpace
	}
	return 0
}

func (x *RequestGetHashSpace) GetEndHashSpace() uint64 {
	if x != nil {
		return x.EndHashSpace
	}
	return 0
}

type RequestGossipJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNodeId     string                 `protobuf:"bytes,1,opt,name=new_node_id,json=newNodeId,proto3" json:"new_node_id,omitempty"`
	Tokens        []uint64               `protobuf:"varint,2,rep,packed,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGossipJoin) Reset() {
	*x = RequestGossipJoin{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGossipJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGossipJoin) ProtoMessage() {}

func (x *RequestGossipJoin) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGossipJoin.ProtoReflect.Descriptor instead.
func (*RequestGossipJoin) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *RequestGossipJoin) GetNewNodeId() string {
	if x != nil {
		return x.NewNodeId
	}
	return ""
}

func (x *RequestGossipJoin) GetTokens() []uint64 {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RequestGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *RequestGet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestPut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPut) Reset() {
	*x = RequestPut{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPut) ProtoMessage() {}

func (x *RequestPut) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPut.ProtoReflect.Descriptor instead.
func (*RequestPut) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *RequestPut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestPut) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RequestDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDelete) Reset() {
	*x = RequestDelete{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelete) ProtoMessage() {}

func (x *RequestDelete) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelete.ProtoReflect.Descriptor instead.
func (*RequestDelete) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *RequestDelete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestHas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHas) Reset() {
	*x = RequestHas{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHas) ProtoMessage() {}

func (x *RequestHas) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHas.ProtoReflect.Descriptor instead.
func (*RequestHas) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *RequestHas) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Response struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Origin string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"` // id of the node that sent the response
	Ok     bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error  string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*Response_Ping
	//	*Response_FetchRing
	//	*Response_GetHashSpace
	//	*Response_GossipJoin
	//	*Response_Get
	//	*Response_Put
	//	*Response_Delete
	//	*Response_Has
	ResponseType  isResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetResponseType() isResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *Response) GetPing() *ResponsePing {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Response) GetFetchRing() *ResponseFetchRing {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_FetchRing); ok {
			return x.FetchRing
		}
	}
	return nil
}

func (x *Response) GetGetHashSpace() *ResponseGetHashSpace {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_GetHashSpace); ok {
			return x.GetHashSpace
		}
	}
	return nil
}

func (x *Response) GetGossipJoin() *ResponseGossipJoin {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_GossipJoin); ok {
			return x.GossipJoin
		}
	}
	return nil
}

func (x *Response) GetGet() *ResponseGet {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Response) GetPut() *ResponsePut {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Response) GetDelete() *ResponseDelete {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Response) GetHas() *ResponseHas {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_Has); ok {
			return x.Has
		}
	}
	return nil
}

type isResponse_ResponseType interface {
	isResponse_ResponseType()
}

type Response_Ping struct {
	Ping *ResponsePing `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

type Response_FetchRing struct {
	FetchRing *ResponseFetchRing `protobuf:"bytes,12,opt,name=fetch_ring,json=fetchRing,proto3,oneof"`
}

type Response_GetHashSpace struct {
	GetHashSpace *ResponseGetHashSpace `protobuf:"bytes,13,opt,name=get_hash_space,json=getHashSpace,proto3,oneof"`
}

type Response_GossipJoin struct {
	GossipJoin *ResponseGossipJoin `protobuf:"bytes,14,opt,name=gossip_join,json=gossipJoin,proto3,oneof"`
}

type Response_Get struct {
	Get *ResponseGet `protobuf:"bytes,15,opt,name=get,proto3,oneof"`
}

type Response_Put struct {
	Put *ResponsePut `protobuf:"bytes,16,opt,name=put,proto3,oneof"`
}

type Response_Delete struct {
	Delete *ResponseDelete `protobuf:"bytes,17,opt,name=delete,proto3,oneof"`
}

type Response_Has struct {
	Has *ResponseHas `protobuf:"bytes,18,opt,name=has,proto3,oneof"`
}

func (*Response_Ping) isResponse_ResponseType() {}

func (*Response_FetchRing) isResponse_ResponseType() {}

func (*Response_GetHashSpace) isResponse_ResponseType() {}

func (*Response_GossipJoin) isResponse_ResponseType() {}

func (*Response_Get) isResponse_ResponseType() {}

func (*Response_Put) isResponse_ResponseType() {}

func (*Response_Delete) isResponse_ResponseType() {}

func (*Response_Has) isResponse_ResponseType() {}

type ResponsePing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PongMessage   string                 `protobuf:"bytes,1,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePing) Reset() {
	*x = ResponsePing{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePing) ProtoMessage() {}

func (x *ResponsePing) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePing.ProtoReflect.Descriptor instead.
func (*ResponsePing) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *ResponsePing) GetPongMessage() string {
	if x != nil {
		return x.PongMessage
	}
	return ""
}

type ResponseFetchRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenToNode   map[uint64]string      `protobuf:"bytes,1,rep,name=token_to_node,json=tokenToNode,proto3" json:"token_to_node,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFetchRing) Reset() {
	*x = ResponseFetchRing{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFetchRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFetchRing) ProtoMessage() {}

func (x *ResponseFetchRing) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFetchRing.ProtoReflect.Descriptor instead.
func (*ResponseFetchRing) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseFetchRing) GetTokenToNode() map[uint64]string {
	if x != nil {
		return x.TokenToNode
	}
	return nil
}

type ResponseGetHashSpace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetHashSpace) Reset() {
	*x = ResponseGetHashSpace{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetHashSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetHashSpace) ProtoMessage() {}

func (x *ResponseGetHashSpace) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetHashSpace.ProtoReflect.Descriptor instead.
func (*ResponseGetHashSpace) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

type ResponseGossipJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGossipJoin) Reset() {
	*x = ResponseGossipJoin{}
	mi := &file_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGossipJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGossipJoin) ProtoMessage() {}

func (x *ResponseGossipJoin) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGossipJoin.ProtoReflect.Descriptor instead.
func (*ResponseGossipJoin) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{13}
}

type ResponseGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGet) Reset() {
	*x = ResponseGet{}
	mi := &file_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGet) ProtoMessage() {}

func (x *ResponseGet) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGet.ProtoReflect.Descriptor instead.
func (*ResponseGet) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseGet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponsePut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePut) Reset() {
	*x = ResponsePut{}
	mi := &file_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePut) ProtoMessage() {}

func (x *ResponsePut) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePut.ProtoReflect.Descriptor instead.
func (*ResponsePut) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{15}
}

type ResponseDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDelete) Reset() {
	*x = ResponseDelete{}
	mi := &file_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDelete) ProtoMessage() {}

func (x *ResponseDelete) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDelete.ProtoReflect.Descriptor instead.
func (*ResponseDelete) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{16}
}

type ResponseHas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasKey        bool                   `protobuf:"varint,1,opt,name=has_key,json=hasKey,proto3" json:"has_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHas) Reset() {
	*x = ResponseHas{}
	mi := &file_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHas) ProtoMessage() {}

func (x *ResponseHas) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHas.ProtoReflect.Descriptor instead.
func (*ResponseHas) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{17}
}

func (x *ResponseHas) GetHasKey() bool {
	if x != nil {
		return x.HasKey
	}
	return false
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\"\x8b\x03\n" +
	"\aRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\"\n" +
	"\x04ping\x18\v \x01(\v2\f.RequestPingH\x00R\x04ping\x122\n" +
	"\n" +
	"fetch_ring\x18\f \x01(\v2\x11.RequestFetchRingH\x00R\tfetchRing\x12<\n" +
	"\x0eget_hash_space\x18\r \x01(\v2\x14.RequestGetHashSpaceH\x00R\fgetHashSpace\x125\n" +
	"\vgossip_join\x18\x0e \x01(\v2\x12.RequestGossipJoinH\x00R\n" +
	"gossipJoin\x12\x1f\n" +
	"\x03get\x18\x0f \x01(\v2\v.RequestGetH\x00R\x03get\x12\x1f\n" +
	"\x03put\x18\x10 \x01(\v2\v.RequestPutH\x00R\x03put\x12(\n" +
	"\x06delete\x18\x11 \x01(\v2\x0e.RequestDeleteH\x00R\x06delete\x12\x1f\n" +
	"\x03has\x18\x12 \x01(\v2\v.RequestHasH\x00R\x03hasB\x0e\n" +
	"\frequest_type\"\r\n" +
	"\vRequestPing\"\x12\n" +
	"\x10RequestFetchRing\"e\n" +
	"\x13RequestGetHashSpace\x12(\n" +
	"\x10start_hash_space\x18\x01 \x01(\x04R\x0estartHashSpace\x12$\n" +
	"\x0eend_hash_space\x18\x02 \x01(\x04R\fendHashSpace\"K\n" +
	"\x11RequestGossipJoin\x12\x1e\n" +
	"\vnew_node_id\x18\x01 \x01(\tR\tnewNodeId\x12\x16\n" +
	"\x06tokens\x18\x02 \x03(\x04R\x06tokens\"\x1e\n" +
	"\n" +
	"RequestGet\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"4\n" +
	"\n" +
	"RequestPut\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"!\n" +
	"\rRequestDelete\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1e\n" +
	"\n" +
	"RequestHas\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xbb\x03\n" +
	"\bResponse\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12#\n" +
	"\x04ping\x18\v \x01(\v2\r.ResponsePingH\x00R\x04ping\x123\n" +
	"\n" +
	"fetch_ring\x18\f \x01(\v2\x12.ResponseFetchRingH\x00R\tfetchRing\x12=\n" +
	"\x0eget_hash_space\x18\r \x01(\v2\x15.ResponseGetHashSpaceH\x00R\fgetHashSpace\x126\n" +
	"\vgossip_join\x18\x0e \x01(\v2\x13.ResponseGossipJoinH\x00R\n" +
	"gossipJoin\x12 \n" +
	"\x03get\x18\x0f \x01(\v2\f.ResponseGetH\x00R\x03get\x12 \n" +
	"\x03put\x18\x10 \x01(\v2\f.ResponsePutH\x00R\x03put\x12)\n" +
	"\x06delete\x18\x11 \x01(\v2\x0f.ResponseDeleteH\x00R\x06delete\x12 \n" +
	"\x03has\x18\x12 \x01(\v2\f.ResponseHasH\x00R\x03hasB\x0f\n" +
	"\rresponse_type\"1\n" +
	"\fResponsePing\x12!\n" +
	"\fpong_message\x18\x01 \x01(\tR\vpongMessage\"\x9c\x01\n" +
	"\x11ResponseFetchRing\x12G\n" +
	"\rtoken_to_node\x18\x01 \x03(\v2#.ResponseFetchRing.TokenToNodeEntryR\vtokenToNode\x1a>\n" +
	"\x10TokenToNodeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14ResponseGetHashSpace\"\x14\n" +
	"\x12ResponseGossipJoin\"#\n" +
	"\vResponseGet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\r\n" +
	"\vResponsePut\"\x10\n" +
	"\x0eResponseDelete\"&\n" +
	"\vResponseHas\x12\x17\n" +
	"\ahas_key\x18\x01 \x01(\bR\x06hasKeyB'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_node_proto_goTypes = []any{
	(*Request)(nil),              // 0: Request
	(*RequestPing)(nil),          // 1: RequestPing
	(*RequestFetchRing)(nil),     // 2: RequestFetchRing
	(*RequestGetHashSpace)(nil),  // 3: RequestGetHashSpace
	(*RequestGossipJoin)(nil),    // 4: RequestGossipJoin
	(*RequestGet)(nil),           // 5: RequestGet
	(*RequestPut)(nil),           // 6: RequestPut
	(*RequestDelete)(nil),        // 7: RequestDelete
	(*RequestHas)(nil),           // 8: RequestHas
	(*Response)(nil),             // 9: Response
	(*ResponsePing)(nil),         // 10: ResponsePing
	(*ResponseFetchRing)(nil),    // 11: ResponseFetchRing
	(*ResponseGetHashSpace)(nil), // 12: ResponseGetHashSpace
	(*ResponseGossipJoin)(nil),   // 13: ResponseGossipJoin
	(*ResponseGet)(nil),          // 14: ResponseGet
	(*ResponsePut)(nil),          // 15: ResponsePut
	(*ResponseDelete)(nil),       // 16: ResponseDelete
	(*ResponseHas)(nil),          // 17: ResponseHas
	nil,                          // 18: ResponseFetchRing.TokenToNodeEntry
}
var file_node_proto_depIdxs = []int32{
	1,  // 0: Request.ping:type_name -> RequestPing
	2,  // 1: Request.fetch_ring:type_name -> RequestFetchRing
	3,  // 2: Request.get_hash_space:type_name -> RequestGetHashSpace
	4,  // 3: Request.gossip_join:type_name -> RequestGossipJoin
	5,  // 4: Request.get:type_name -> RequestGet
	6,  // 5: Request.put:type_name -> RequestPut
	7,  // 6: Request.delete:type_name -> RequestDelete
	8,  // 7: Request.has:type_name -> RequestHas
	10, // 8: Response.ping:type_name -> ResponsePing
	11, // 9: Response.fetch_ring:type_name -> ResponseFetchRing
	12, // 10: Response.get_hash_space:type_name -> ResponseGetHashSpace
	13, // 11: Response.gossip_join:type_name -> ResponseGossipJoin
	14, // 12: Response.get:type_name -> ResponseGet
	15, // 13: Response.put:type_name -> ResponsePut
	16, // 14: Response.delete:type_name -> ResponseDelete
	17, // 15: Response.has:type_name -> ResponseHas
	18, // 16: ResponseFetchRing.token_to_node:type_name -> ResponseFetchRing.TokenToNodeEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Ping)(nil),
		(*Request_FetchRing)(nil),
		(*Request_GetHashSpace)(nil),
		(*Request_GossipJoin)(nil),
		(*Request_Get)(nil),
		(*Request_Put)(nil),
		(*Request_Delete)(nil),
		(*Request_Has)(nil),
	}
	file_node_proto_msgTypes[9].OneofWrappers = []any{
		(*Response_Ping)(nil),
		(*Response_FetchRing)(nil),
		(*Response_GetHashSpace)(nil),
		(*Response_GossipJoin)(nil),
		(*Response_Get)(nil),
		(*Response_Put)(nil),
		(*Response_Delete)(nil),
		(*Response_Has)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
