// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: shopping.proto

package g01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoppingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      *CCounter              `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Acquired      *CCounter              `protobuf:"bytes,3,opt,name=acquired,proto3" json:"acquired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingItem) Reset() {
	*x = ShoppingItem{}
	mi := &file_shopping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingItem) ProtoMessage() {}

func (x *ShoppingItem) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingItem.ProtoReflect.Descriptor instead.
func (*ShoppingItem) Descriptor() ([]byte, []int) {
	return file_shopping_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShoppingItem) GetQuantity() *CCounter {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *ShoppingItem) GetAcquired() *CCounter {
	if x != nil {
		return x.Acquired
	}
	return nil
}

type ShoppingItemsORMap struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         map[string]*ShoppingItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingItemsORMap) Reset() {
	*x = ShoppingItemsORMap{}
	mi := &file_shopping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingItemsORMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingItemsORMap) ProtoMessage() {}

func (x *ShoppingItemsORMap) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingItemsORMap.ProtoReflect.Descriptor instead.
func (*ShoppingItemsORMap) Descriptor() ([]byte, []int) {
	return file_shopping_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingItemsORMap) GetItems() map[string]*ShoppingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ItemsOrmap    *ShoppingItemsORMap    `protobuf:"bytes,4,opt,name=items_ormap,json=itemsOrmap,proto3" json:"items_ormap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingList) Reset() {
	*x = ShoppingList{}
	mi := &file_shopping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingList) ProtoMessage() {}

func (x *ShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingList.ProtoReflect.Descriptor instead.
func (*ShoppingList) Descriptor() ([]byte, []int) {
	return file_shopping_proto_rawDescGZIP(), []int{2}
}

func (x *ShoppingList) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoppingList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShoppingList) GetItemsOrmap() *ShoppingItemsORMap {
	if x != nil {
		return x.ItemsOrmap
	}
	return nil
}

var File_shopping_proto protoreflect.FileDescriptor

const file_shopping_proto_rawDesc = "" +
	"\n" +
	"\x0eshopping.proto\x1a\n" +
	"crdt.proto\"p\n" +
	"\fShoppingItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\bquantity\x18\x02 \x01(\v2\t.CCounterR\bquantity\x12%\n" +
	"\bacquired\x18\x03 \x01(\v2\t.CCounterR\bacquired\"\x93\x01\n" +
	"\x12ShoppingItemsORMap\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.ShoppingItemsORMap.ItemsEntryR\x05items\x1aG\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.ShoppingItemR\x05value:\x028\x01\"\x87\x01\n" +
	"\fShoppingList\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x124\n" +
	"\vitems_ormap\x18\x04 \x01(\v2\x13.ShoppingItemsORMapR\n" +
	"itemsOrmapB'Z%gitlab.up.pt/classes/sdle/2025/t2/g01b\x06proto3"

var (
	file_shopping_proto_rawDescOnce sync.Once
	file_shopping_proto_rawDescData []byte
)

func file_shopping_proto_rawDescGZIP() []byte {
	file_shopping_proto_rawDescOnce.Do(func() {
		file_shopping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopping_proto_rawDesc), len(file_shopping_proto_rawDesc)))
	})
	return file_shopping_proto_rawDescData
}

var file_shopping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shopping_proto_goTypes = []any{
	(*ShoppingItem)(nil),       // 0: ShoppingItem
	(*ShoppingItemsORMap)(nil), // 1: ShoppingItemsORMap
	(*ShoppingList)(nil),       // 2: ShoppingList
	nil,                        // 3: ShoppingItemsORMap.ItemsEntry
	(*CCounter)(nil),           // 4: CCounter
}
var file_shopping_proto_depIdxs = []int32{
	4, // 0: ShoppingItem.quantity:type_name -> CCounter
	4, // 1: ShoppingItem.acquired:type_name -> CCounter
	3, // 2: ShoppingItemsORMap.items:type_name -> ShoppingItemsORMap.ItemsEntry
	1, // 3: ShoppingList.items_ormap:type_name -> ShoppingItemsORMap
	0, // 4: ShoppingItemsORMap.ItemsEntry.value:type_name -> ShoppingItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shopping_proto_init() }
func file_shopping_proto_init() {
	if File_shopping_proto != nil {
		return
	}
	file_crdt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopping_proto_rawDesc), len(file_shopping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shopping_proto_goTypes,
		DependencyIndexes: file_shopping_proto_depIdxs,
		MessageInfos:      file_shopping_proto_msgTypes,
	}.Build()
	File_shopping_proto = out.File
	file_shopping_proto_goTypes = nil
	file_shopping_proto_depIdxs = nil
}
